kind: pipeline
name: tests and coverage
type: docker

steps:
- name: test
  image: python:3.8-slim-buster
  commands:
    - pip install -r requirements/dev.txt
    - flake8
    - PYTHONPATH=. coverage run --source=softlab -m pytest
    - coverage xml -o report.xml

- name: upload to codecov
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
      files:
        - report.xml

---

kind: pipeline
name: push to github
type: docker

steps:
- name: push to github
  image: appleboy/drone-git-push
  failure: ignore
  settings:
    branch: master
    remote: git@github.com:dmeiburg/softlab.git
    force: false
  environment:
    PLUGIN_SSH_KEY:
      from_secret: github_ssh_key
  when:
    branch:
      - master
